version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: etl_postgres
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  streamlit:
    build: .
    command: streamlit run etl/dashboard.py --server.port=8501 --server.address=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - db

  etl:
    build: .
    container_name: etl_pipeline
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://etl_user:etl_pass@db:5432/etl_db
    volumes:
      - .:/app
    working_dir: /app
    command: python etl/main.py

volumes:
  db_data:
